[install]
# Use exact versions by default
exact = true

[install.cache]
# Enable global cache
dir = "~/.bun/install/cache"
disable = false

[test]
# Configure Jest compatibility mode
jsx_pragma = "React.createElement"
jsx_fragment = "React.Fragment"

# Set the default timeout
timeout = 10000 